### ISSUE TITLE
Setting up virtual environment

### ISSUE THREAD

**Issue by yohannjs** [norlab-ulaval/logpiles_segmentation#1]
Hello, 
I am a PhD student also working with research that involves segmentation of logs. I read your paper, and thought that you had attained very good results wrt. instance segmentation of logs. I wanted to test your models on my dataset, but am having trouble setting up the environment. In the README file it seems as though working on a computer with a CUDA-capable GPU is beneficial, but not required. However, when I try to set up the environment as per the instructions in the README I am unable to download many of the packages. The following packages were not found: 
- caffe2==0.8.1
- mmcv==1.5.0
- mmdet.egg==info
- MultiScaleDeformableAttention==1.0
- torch==1.10.0+cu113
- torchvision==0.11.1+cu113

**Comment by jmfortin** [comment]
Hi, I updated the instructions in the meantime, it should now work correctly. Sorry for the delay !
