### ISSUE TITLE
Some segmentation masks are bad?

### ISSUE THREAD

**Issue by sandeepjana** [norlab-ulaval/logpiles_segmentation#3]
I found a few segmentation masks having less than four points (8 coordinates). For e.g., 
`{'id': 625, 'image_id': 62, 'iscrowd': 0, 'category_id': 0, 'segmentation': [[607.2, 571.36, 606.24, 574.48]], 'bbox': [606.0, 571.0, 0.0, -24.0], 'area': 2.9952000000000965}` in prescaled/coco_annotations.json.

For my experiment, I just removed them...
```
import json
import sys

src = sys.argv[1]
dst = src.replace(".json", "_fixed.json")

with open(src) as f:
    info = json.load(f)
    
anns = info["annotations"]
updated = []

for i in range(len(anns)):
    ann = anns[i]
    seg = ann["segmentation"] 
    if seg is not None and len(seg[0]) < (4 * 2):
        print(f"Bad seg: {ann}")
        continue
    bbox = ann["bbox"]
    if bbox is not None and any(a < 0 for a in bbox):
        print(f"Bad box: {ann}")
        continue
    updated.append(ann)
    
info["annotations"] = updated

print("Writing to ", dst)
with open(dst, "w") as f:
    json.dump(info, f, indent=4)
    

```

**Comment by jmfortin** [comment]
You are right, resizing the images caused some masks to shrink smaller than 4 points. I believe that Detectron2 automatically filters them though. Thanks for the info!
